### ISSUE TITLE
RuntimeError: Failed to install dependency package.

### ISSUE THREAD

**Issue by almereyda** [nixjdm/lektor-tags#9]
After adding this plugin to a lektor site, the following appears and breaks the plugin to work:

```
Collecting tags==0.0.3                 
  Using cached tags-0.0.3.tar.gz       
    Complete output from command python setup.py egg_info:                     
    Traceback (most recent call last): 
      File "<string>", line 1, in <module>                                     
      File "/tmp/pip-build-QntePn/tags/setup.py", line 12, in <module>         
        long_description = open('description.rst', 'r').read(),                
    IOError: [Errno 2] No such file or directory: 'description.rst'            
                                       
    ----------------------------------------                                   
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-QntePn/tags/                                                                     
Traceback (most recent call last):     
  File "/usr/bin/lektor", line 11, in <module>                                 
    sys.exit(main())                   
  File "/lib/lektor/lib/python2.7/site-packages/click/core.py", line 722, in __call__                                                                          
    return self.main(*args, **kwargs)  
  File "/lib/lektor/lib/python2.7/site-packages/click/core.py", line 697, in main                                                                              
    rv = self.invoke(ctx)              
  File "/lib/lektor/lib/python2.7/site-packages/click/core.py", line 1066, in invoke                                                                           
    return _process_result(sub_ctx.command.invoke(sub_ctx))                    
  File "/lib/lektor/lib/python2.7/site-packages/click/core.py", line 1066, in invoke                                                                           
    return _process_result(sub_ctx.command.invoke(sub_ctx))                    
  File "/lib/lektor/lib/python2.7/site-packages/click/core.py", line 895, in invoke                                                                            
    return ctx.invoke(self.callback, **ctx.params)                             
  File "/lib/lektor/lib/python2.7/site-packages/click/core.py", line 535, in invoke                                                                            
    return callback(*args, **kwargs)   
  File "/lib/lektor/lib/python2.7/site-packages/click/decorators.py", line 64, in new_func                                                                     
    return ctx.invoke(f, obj, *args[1:], **kwargs)                             
  File "/lib/lektor/lib/python2.7/site-packages/click/core.py", line 535, in invoke                                                                            
    return callback(*args, **kwargs)   
  File "/lib/lektor/lib/python2.7/site-packages/lektor/cli.py", line 509, in plugins_list_cmd                                                                  
    ctx.load_plugins()                 
  File "/lib/lektor/lib/python2.7/site-packages/lektor/cli.py", line 96, in load_plugins                                                                       
    load_packages(self.get_env(), reinstall=reinstall)                         
  File "/lib/lektor/lib/python2.7/site-packages/lektor/packages.py", line 304, in load_packages                                                                
    refresh=reinstall)                 
  File "/lib/lektor/lib/python2.7/site-packages/lektor/packages.py", line 274, in update_cache                                                                 
    download_and_install_package(package_root, package, version)               
  File "/lib/lektor/lib/python2.7/site-packages/lektor/packages.py", line 103, in download_and_install_package                                                 
    raise RuntimeError('Failed to install dependency package.')                
```

**Comment by almereyda** [comment]
Running `lektor plugins remove lektor-tags` before and after `lektor plugins flush-cache` is also not working.

    Package was not registered with the project.  Nothing was removed.

**Comment by nixjdm** [comment]
The first snippet looks like a failure to install. Removing it after that wouldn't work because it isn't there to remove.

As for why your install failed, I wish your snippet contained your actual command. I don't see where `tags==0.0.3` is coming from. As far as I can tell, the version in this repo was always `0.1`, so where' you get `0.0.3`? There is also no line matching `long_description = open('description.rst', 'r').read()` in the setup.py. I'm thinking you were installing something else entirely.

**Comment by nixjdm** [comment]
Closing this due to age and I think that your version was wrong. If something similar is still an issue, please raise another ticket.
